Shoppingcart
icecoldgeiten/Nerdygadgets pull request #6
Opened 2020-11-16 15:09 UTC by BB1-23

2020-11-16 15:31 UTC, icecoldgeiten requested changes

2020-11-16 15:31 UTC, icecoldgeiten commented on cartfunctions.php
> +            $cart = $_SESSION['cart']; // zo ja: ophalen
Je geeft $ID mee aan de functie maar vervolgens doe je in de functie niks met $ID

2020-11-16 15:31 UTC, icecoldgeiten commented on view.php
> +AddToCart($stockItemID);
Dit word altijd aangeroepen? Wat gebeurt als $stockitemID leeg is?

2020-11-16 15:31 UTC, icecoldgeiten commented on Public/CSS/Style.css
> +    background-color: blue;
Hier staat nog een comment

2020-11-17 07:34 UTC, BB1-23 commented on Public/CSS/Style.css
> +    background-color: blue;
Voor volgende sprint

2020-11-17 08:09 UTC, icecoldgeiten approved these changes

2020-11-17 08:09 UTC, merged